# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = "eventbrite"
  s.version = "0.4.1"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["David Haslem"]
  s.date = "2012-04-15"
  s.description = "A simple, unoffical gem that integrates with the EventBrite events service. (http://www.eventbrite.com)"
  s.email = "therabidbanana@gmail.com"
  s.extra_rdoc_files = [
    "LICENSE",
    "README.markdown"
  ]
  s.files         = `git ls-files`.split("\n")
  s.test_files    = `git ls-files -- {test,spec,features}/*`.split("\n")
  s.executables   = `git ls-files -- bin/*`.split("\n").map{ |f| File.basename(f) }
  s.homepage = "http://github.com/therabidbanana/eventbrite"
  s.require_paths = ["lib"]
  s.rubygems_version = "1.8.12"
  s.summary = "An unofficial gem for EventBrite Integration"

  s.add_development_dependency(%q<rspec>, "~> 2.0")
  s.add_dependency(%q<httparty>, "~> 0.8.0")
  s.add_dependency(%q<tzinfo>, "~> 0.3.22")
end

